In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('Housing.csv')

In [3]:
df.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [4]:
df.shape

(545, 13)

In [5]:
df.describe()

price          area    bedrooms   bathrooms     stories  \
count  5.450000e+02    545.000000  545.000000  545.000000  545.000000   
mean   4.766729e+06   5150.541284    2.965138    1.286239    1.805505   
std    1.870440e+06   2170.141023    0.738064    0.502470    0.867492   
min    1.750000e+06   1650.000000    1.000000    1.000000    1.000000   
25%    3.430000e+06   3600.000000    2.000000    1.000000    1.000000   
50%    4.340000e+06   4600.000000    3.000000    1.000000    2.000000   
75%    5.740000e+06   6360.000000    3.000000    2.000000    2.000000   
max    1.330000e+07  16200.000000    6.000000    4.000000    4.000000   

          parking  
count  545.000000  
mean     0.693578  
std      0.861586  
min      0.000000  
25%      0.000000  
50%      0.000000  
75%      1.000000  
max      3.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
price               545 non-null int64
area                545 non-null int64
bedrooms            545 non-null int64
bathrooms           545 non-null int64
stories             545 non-null int64
mainroad            545 non-null object
guestroom           545 non-null object
basement            545 non-null object
hotwaterheating     545 non-null object
airconditioning     545 non-null object
parking             545 non-null int64
prefarea            545 non-null object
furnishingstatus    545 non-null object
dtypes: int64(6), object(7)
memory usage: 55.4+ KB


In [7]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

# Label Encoding

In [8]:
list=['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea']
def binmap(x):
    return x.map({'yes':1,'no':0})
df[list]=df[list].apply(binmap)

In [9]:
df.head()

price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0  13300000  7420         4          2        3         1          0   
1  12250000  8960         4          4        4         1          0   
2  12250000  9960         3          2        2         1          0   
3  12215000  7500         4          2        2         1          0   
4  11410000  7420         4          1        2         1          1   

   basement  hotwaterheating  airconditioning  parking  prefarea  \
0         0                0                1        2         1   
1         0                0                1        3         0   
2         1                0                0        2         1   
3         1                0                1        3         1   
4         1                0                1        2         0   

  furnishingstatus  
0        furnished  
1        furnished  
2   semi-furnished  
3        furnished  
4        furnished

# One Hot Encoding

In [10]:
status=pd.get_dummies(df['furnishingstatus'])

In [11]:
status.head()

furnished  semi-furnished  unfurnished
0          1               0            0
1          1               0            0
2          0               1            0
3          1               0            0
4          1               0            0

In [12]:
df.drop(['furnishingstatus'],axis=1,inplace=True)
df=pd.concat([df,status],axis=1)

In [13]:
df.head()

price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0  13300000  7420         4          2        3         1          0   
1  12250000  8960         4          4        4         1          0   
2  12250000  9960         3          2        2         1          0   
3  12215000  7500         4          2        2         1          0   
4  11410000  7420         4          1        2         1          1   

   basement  hotwaterheating  airconditioning  parking  prefarea  furnished  \
0         0                0                1        2         1          1   
1         0                0                1        3         0          1   
2         1                0                0        2         1          0   
3         1                0                1        3         1          1   
4         1                0                1        2         0          1   

   semi-furnished  unfurnished  
0               0            0  
1               0            0  
2               1            0  
3               0            0  
4               0            0

# Independent & Dependent Variable

In [14]:
y=df.pop('price').values
x=df.values

In [15]:
x

array([[7420,    4,    2, ...,    1,    0,    0],
       [8960,    4,    4, ...,    1,    0,    0],
       [9960,    3,    2, ...,    0,    1,    0],
       ...,
       [3620,    2,    1, ...,    0,    0,    1],
       [2910,    3,    1, ...,    1,    0,    0],
       [3850,    3,    1, ...,    0,    0,    1]], dtype=int64)

In [16]:
y

array([13300000, 12250000, 12250000, 12215000, 11410000, 10850000,
       10150000, 10150000,  9870000,  9800000,  9800000,  9681000,
        9310000,  9240000,  9240000,  9100000,  9100000,  8960000,
        8890000,  8855000,  8750000,  8680000,  8645000,  8645000,
        8575000,  8540000,  8463000,  8400000,  8400000,  8400000,
        8400000,  8400000,  8295000,  8190000,  8120000,  8080940,
        8043000,  7980000,  7962500,  7910000,  7875000,  7840000,
        7700000,  7700000,  7560000,  7560000,  7525000,  7490000,
        7455000,  7420000,  7420000,  7420000,  7350000,  7350000,
        7350000,  7350000,  7343000,  7245000,  7210000,  7210000,
        7140000,  7070000,  7070000,  7035000,  7000000,  6930000,
        6930000,  6895000,  6860000,  6790000,  6790000,  6755000,
        6720000,  6685000,  6650000,  6650000,  6650000,  6650000,
        6650000,  6650000,  6629000,  6615000,  6615000,  6580000,
        6510000,  6510000,  6510000,  6475000,  6475000,  6440

# Train, Test & Split

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [18]:
x_train.shape

(436, 14)

In [19]:
x_test.shape

(109, 14)

# Multiple Linear Regression

In [20]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [21]:
lr_pred=lr.predict(x_test)

In [22]:
lr_pred

array([ 3950288.61876184,  6173868.81883112,  4483635.98836252,
        7258732.75105287,  2836727.58490483,  7032947.09749074,
        3203851.47112392,  3270994.00904055,  3472554.03645915,
        8289978.32623725,  6605321.62954623,  3723366.23684094,
        3812376.95976085,  4548966.8454461 ,  4020476.34849668,
        1969836.22090135,  4057262.98087852,  3704586.86711741,
        3282767.93188792,  4609423.64909564,  5968243.7363716 ,
        6363698.62063814,  4751300.32389   ,  2659595.27633028,
        5305573.24662117,  5680819.58784461,  5404106.90027142,
        5543050.52192535,  5768360.47982208,  5801753.70839283,
        3389277.96110608,  6399092.02678424,  7081030.31411775,
        2913042.40387669,  4498664.01335423,  5210561.68059367,
        5013457.84122311,  3707596.71347575,  2916603.4548534 ,
        3937761.75634066,  8041334.20180917,  4942174.61142059,
        6432605.2198175 ,  3511338.78156424,  3813475.39540795,
        6434856.19540026,  4447687.02885

In [23]:
from sklearn.metrics import r2_score
lr_acc=r2_score(lr_pred,y_test)

In [24]:
lr_acc

0.5937992792615878

# Decision Tree Regression

In [25]:
type(x_train)

numpy.ndarray

In [26]:
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor()
dtr.fit(x_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [27]:
dtr_pred=dtr.predict(x_test)

In [28]:
dtr_pred

array([ 4907000.,  5250000.,  5145000.,  5600000.,  2940000.,  6650000.,
        3430000.,  4193000.,  5250000.,  6930000.,  5775000.,  3500000.,
        3640000.,  4900000.,  4900000.,  2240000.,  4900000.,  4900000.,
        3640000.,  3640000.,  7420000.,  9681000.,  5740000.,  2100000.,
        5600000.,  6405000.,  5229000.,  5873000.,  4767000.,  5110000.,
        3605000.,  4900000.,  9870000.,  3423000.,  3640000.,  5950000.,
        4200000.,  3640000.,  2660000.,  4200000.,  8575000.,  5600000.,
        5250000.,  2940000.,  5250000.,  6650000.,  3990000.,  3423000.,
        4515000.,  4200000.,  4403000.,  5250000.,  2100000.,  3710000.,
        3500000.,  4200000.,  8043000.,  4403000.,  3675000.,  2940000.,
        3500000.,  5600000.,  3885000.,  7560000.,  2940000.,  5110000.,
        9100000.,  2590000.,  4060000.,  5950000.,  3447500.,  8645000.,
        4550000.,  4340000.,  4445000.,  4403000.,  2940000., 10150000.,
        3353000.,  4690000.,  3447500.,  4480000., 

In [29]:
dtr_acc=r2_score(dtr_pred,y_test)

In [30]:
dtr_acc

0.31923553830985785

# Random Forest Regression

In [31]:
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor(n_estimators=6,random_state=0)
rfr.fit(x_train,y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=6, n_jobs=None,
                      oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

In [32]:
rfr_pred=rfr.predict(x_test)

In [33]:
rfr_pred

array([ 4387833.33333333,  5637333.33333333,  4771666.66666667,
        6760833.33333333,  2902083.33333333,  7045500.        ,
        3570000.        ,  3638833.33333333,  3196666.66666667,
        8096666.66666667,  6410833.33333333,  3179166.66666667,
        4228000.        ,  5495000.        ,  5399333.33333333,
        2286666.66666667,  4124166.66666667,  5080833.33333333,
        3535000.        ,  3785833.33333333,  7665000.        ,
        6358333.33333333,  4335333.33333333,  2496666.66666667,
        6335000.        ,  4806666.66666667,  5568500.        ,
        5399333.33333333,  4207000.        ,  6358333.33333333,
        3878000.        ,  4722083.33333333,  7536666.66666667,
        3228166.66666667,  4736666.66666667,  4175500.        ,
        6800500.        ,  3645833.33333333,  3330833.33333333,
        4223333.33333333,  8457166.66666667,  6644166.66666667,
        7256666.66666667,  3901333.33333333,  3929333.33333333,
        6498333.33333333,  5332833.33333

In [34]:
rfr_acc=r2_score(rfr_pred,y_test)

In [35]:
rfr_acc

0.5179224002783633

# Accuracies of the models

In [36]:
print('Linear Regression = ',lr_acc)
print('Random Forest = ',rfr_acc)
print('Decision Tree = ',dtr_acc)

Linear Regression =  0.5937992792615878
Random Forest =  0.5179224002783633
Decision Tree =  0.31923553830985785
